services:
  nvidia_gpu_exporter:
    image: utkuozdemir/nvidia_gpu_exporter:1.3.1
    container_name: nvidia_gpu_exporter
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "9835:9835"  # Port par défaut pour les métriques Prometheus
    restart: unless-stopped
