services:
  process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process-exporter
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - ./process-exporter-config:/config
    command:
      - "--procfs=/host/proc"
      - "--config.path=/config/config.yml"
    ports:
      - "9256:9256"

